-- ---------------------------------------------------------------------------
-- Partner portal — deal registration.
--
-- Apply AFTER 0003_partner_decisions.sql, in the Supabase SQL editor (or
-- `supabase db push` if the CLI is linked). Safe to re-run.
--
-- Why this table exists: deal registration is the one thing a partner
-- programme is actually FOR. A partner tells us about an opportunity before
-- they work it, and in exchange that opportunity is protected — nobody else
-- gets paid on it. Until now the dashboard's "Register a deal" control was
-- inert and every figure on the page read "—".
--
-- Design notes, following 0001–0003 exactly:
--
--   * SELECT POLICIES ONLY. No insert, update or delete policy anywhere, on
--     purpose. The browser's publishable key physically cannot write this
--     table. Every write goes through a server route holding the service-role
--     key. That single fact is what makes `status` and `reference`
--     unforgeable: a partner cannot register a deal already approved, cannot
--     approve their own, and cannot mint a reference that collides with or
--     impersonates another.
--
--   * `reference` is UNIQUE and generated SERVER-SIDE (DL-XXXXXX). It is the
--     human handle used in email and on the phone. Accepting it from the
--     client would let a partner choose one that looks like someone else's.
--
--   * `status` defaults to 'submitted' AND the route sets it explicitly. Belt
--     and braces: a default is not a guarantee if a future writer passes a
--     value, and the check constraint is the last line.
--
--   * `industry` and `platform` are check-constrained rather than lookup
--     tables. Four and two values respectively, changing about never; a join
--     table here would be ceremony. The same lists live in lib/deal.ts and
--     the route validates against THOSE, so a bad value is a 422 rather than
--     a Postgres error surfacing as a 500. Keep the two in step — the
--     constraint is the backstop, not the validator.
--
--   * `decided_by` references partners on delete SET NULL, matching
--     partner_decisions: a record that erases itself when staff leave is not
--     a record. There is deliberately NO separate deal audit-log table yet —
--     a deal has one decision, unlike a partner account which can be
--     approved, rejected and re-approved. If deals ever gain that, copy the
--     partner_decisions shape.
-- ---------------------------------------------------------------------------

create table if not exists public.deals (
  id                  uuid primary key default gen_random_uuid(),
  partner_id          uuid not null references public.partners (id) on delete cascade,
  -- Human reference, e.g. DL-7QK3M2. Generated by the server, never posted.
  reference           text not null unique,
  customer_name       text not null,
  customer_email      text not null,
  industry            text not null check (industry in ('seaport', 'warehouse', 'airport', 'enterprise')),
  platform            text not null check (platform in ('visopercept', 'tracksure')),
  estimated_value_usd numeric(14, 2) not null check (estimated_value_usd >= 0),
  notes               text,
  status              text not null default 'submitted'
                        check (status in ('submitted', 'approved', 'rejected')),
  rejection_reason    text,
  decided_at          timestamptz,
  decided_by          uuid references public.partners (id) on delete set null,
  created_at          timestamptz not null default now()
);

-- The partner dashboard's only query: this partner's deals, newest first.
create index if not exists deals_partner_idx
  on public.deals (partner_id, created_at desc);

-- The admin queue. Partial, because the queue is the work and it stays small
-- while the table grows without bound.
create index if not exists deals_submitted_idx
  on public.deals (created_at desc)
  where status = 'submitted';

alter table public.deals enable row level security;

drop policy if exists "partners read own deals" on public.deals;
drop policy if exists "admins read every deal"  on public.deals;

create policy "partners read own deals"
  on public.deals for select
  to authenticated
  using (partner_id = auth.uid());

-- Same SECURITY DEFINER helper as 0001. A policy that queried `partners`
-- inline would be fine here (deals is not partners, so no recursion), but
-- using is_admin() keeps one definition of "who is an admin" in the schema.
create policy "admins read every deal"
  on public.deals for select
  to authenticated
  using (public.is_admin());

-- No insert/update/delete policy on purpose. Writes come from
-- app/api/deal-register/route.ts and app/api/deal-decide/route.ts on the
-- service-role key.
